"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const car_1 = require("./car");
const gol = new car_1.Car('Volkswagen', car_1.Colors.SILVER, 4);
gol.openTheDoor(car_1.Doors.DRIVER);
gol.closeTheDoor(car_1.Doors.DRIVER);
gol.turnOn();
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.LEFT);
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.LEFT);
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.RIGHT);
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.RIGHT);
gol.speedDown();
gol.stop();
gol.openTheDoor(car_1.Doors.BEHIND_RIDER);
gol.closeTheDoor(car_1.Doors.BEHIND_RIDER);
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.RIGHT);
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.LEFT);
gol.speedUp();
gol.speedDown();
gol.turn(car_1.Directions.RIGHT);
gol.speedDown();
gol.stop();
gol.openTheDoor(car_1.Doors.BEHIND_RIDER);
gol.closeTheDoor(car_1.Doors.BEHIND_RIDER);
gol.speedUp();
